/*
 * generated by Xtext 2.15.0
 */
package org.xtext.comp.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPyScopeProvider extends DelegatingScopeProvider {
}
