/**
 * generated by Xtext 2.15.0
 */
package org.xtext.compilation.validation;

import org.xtext.compilation.validation.AbstractWhile_lValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class While_lValidator extends AbstractWhile_lValidator {
}
