/**
 * generated by Xtext 2.15.0
 */
package org.xtext.comp.ide;

import org.xtext.comp.ide.AbstractPyIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PyIdeModule extends AbstractPyIdeModule {
}
