/**
 * generated by Xtext 2.15.0
 */
package org.xtext.compilation.scoping;

import org.xtext.compilation.scoping.AbstractWhile_lScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class While_lScopeProvider extends AbstractWhile_lScopeProvider {
}
