/*
 * generated by Xtext 2.15.0
 */
package org.xtext.comp


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PyStandaloneSetup extends PyStandaloneSetupGenerated {

	def static void doSetup() {
		new PyStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
