/*
 * generated by Xtext 2.15.0
 */
package org.xtext.comp.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.comp.wh.ui.internal.WhActivator;

public class PyUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return WhActivator.getInstance().getInjector("org.xtext.comp.Py");
	}

}
