/**
 * generated by Xtext 2.15.0
 */
package org.xtext.compilation.while_l;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.compilation.while_l.Expr#getExpr <em>Expr</em>}</li>
 *   <li>{@link org.xtext.compilation.while_l.Expr#getExprEq <em>Expr Eq</em>}</li>
 * </ul>
 *
 * @see org.xtext.compilation.while_l.While_lPackage#getExpr()
 * @model
 * @generated
 */
public interface Expr extends EObject
{
  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(EObject)
   * @see org.xtext.compilation.while_l.While_lPackage#getExpr_Expr()
   * @model containment="true"
   * @generated
   */
  EObject getExpr();

  /**
   * Sets the value of the '{@link org.xtext.compilation.while_l.Expr#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(EObject value);

  /**
   * Returns the value of the '<em><b>Expr Eq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr Eq</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr Eq</em>' containment reference.
   * @see #setExprEq(ExprEq)
   * @see org.xtext.compilation.while_l.While_lPackage#getExpr_ExprEq()
   * @model containment="true"
   * @generated
   */
  ExprEq getExprEq();

  /**
   * Sets the value of the '{@link org.xtext.compilation.while_l.Expr#getExprEq <em>Expr Eq</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr Eq</em>' containment reference.
   * @see #getExprEq()
   * @generated
   */
  void setExprEq(ExprEq value);

} // Expr
