#!/bin/bash

 cheminSources="./dossierTestsSources"
 cheminResults="./dossierTestsSortie"
 cheminResultats_ok="./dossierTestsPP"

 source=""
 result="result.whpp"
 result_ok=""
 if [ $# = 0 ]
echo "\c" > resultats_test.txt
for i in $cheminSources
do
     source=$i
     result_test=$cheminResults$I$result
     resultat_ok=$cheminResultats_ok

     ./whpp $source -o $result_test
     DIFF=$(diff -u $resultat_ok $result_test)
     echo "$I : Sortie de la comparaison entre le fichier $source et le resultat attendu $ : \c" >>resultats_test.txt
     if [ $DIFF != "" ]
     then
        echo "test reussi!\n" >> resultats_test.txt
     else 
        echo "test non reussi!"
     fi
done
fi
     
