/**
 * generated by Xtext 2.15.0
 */
package org.xtext.compilation;

import org.xtext.compilation.While_lStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class While_lStandaloneSetup extends While_lStandaloneSetupGenerated {
  public static void doSetup() {
    new While_lStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
