/*
 * generated by Xtext 2.15.0
 */
package org.xtext.compilation.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class While_lUiModule extends AbstractWhile_lUiModule {
}
