/*
 * generated by Xtext 2.15.0
 */
package org.xtext.compilation.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWhile_lScopeProvider extends DelegatingScopeProvider {
}
