/**
 * generated by Xtext 2.15.0
 */
package org.xtext.compilation.ui.contentassist;

import org.xtext.compilation.ui.contentassist.AbstractWhile_lProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class While_lProposalProvider extends AbstractWhile_lProposalProvider {
}
