/**
 * generated by Xtext 2.15.0
 */
package org.xtext.compilation.ide;

import org.xtext.compilation.ide.AbstractWhile_lIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class While_lIdeModule extends AbstractWhile_lIdeModule {
}
