/**
 * generated by Xtext 2.15.0
 */
package org.xtext.compilation.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.compilation.While_lRuntimeModule;
import org.xtext.compilation.While_lStandaloneSetup;
import org.xtext.compilation.ide.While_lIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class While_lIdeSetup extends While_lStandaloneSetup {
  @Override
  public Injector createInjector() {
    While_lRuntimeModule _while_lRuntimeModule = new While_lRuntimeModule();
    While_lIdeModule _while_lIdeModule = new While_lIdeModule();
    return Guice.createInjector(Modules2.mixin(_while_lRuntimeModule, _while_lIdeModule));
  }
}
