/*
 * generated by Xtext 2.15.0
 */
package org.xtext.compilation.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.compilation.wh.ui.internal.WhActivator;

public class While_lUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return WhActivator.getInstance().getInjector("org.xtext.compilation.While_l");
	}

}
