/**
 * generated by Xtext 2.15.0
 */
package org.xtext.comp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.comp.ui.AbstractPyUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PyUiModule extends AbstractPyUiModule {
  public PyUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
