/*
 * generated by Xtext 2.15.0
 */
package org.xtext.compilation.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.compilation.parser.antlr.internal.InternalWhile_lParser;
import org.xtext.compilation.services.While_lGrammarAccess;

public class While_lParser extends AbstractAntlrParser {

	@Inject
	private While_lGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalWhile_lParser createParser(XtextTokenStream stream) {
		return new InternalWhile_lParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Wh";
	}

	public While_lGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(While_lGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
