/*
 * generated by Xtext 2.15.0
 */
package org.xtext.compilation.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class While_lAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/compilation/parser/antlr/internal/InternalWhile_l.tokens");
	}
}
