/*
 * generated by Xtext 2.15.0
 */
package org.xtext.compilation


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class While_lStandaloneSetup extends While_lStandaloneSetupGenerated {

	def static void doSetup() {
		new While_lStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
