/**
 * generated by Xtext 2.15.0
 */
package org.xtext.comp.validation;

import org.xtext.comp.validation.AbstractPyValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PyValidator extends AbstractPyValidator {
}
