/**
 * generated by Xtext 2.15.0
 */
package org.xtext.compilation.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.compilation.ui.AbstractWhile_lUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class While_lUiModule extends AbstractWhile_lUiModule {
  public While_lUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
