/**
 * generated by Xtext 2.15.0
 */
package org.xtext.comp;

import org.xtext.comp.AbstractPyRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PyRuntimeModule extends AbstractPyRuntimeModule {
}
