/**
 * generated by Xtext 2.15.0
 */
package org.xtext.comp;

import org.xtext.comp.PyStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PyStandaloneSetup extends PyStandaloneSetupGenerated {
  public static void doSetup() {
    new PyStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
