/*
 * generated by Xtext 2.15.0
 */
package org.xtext.comp.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.comp.PyRuntimeModule
import org.xtext.comp.PyStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class PyIdeSetup extends PyStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new PyRuntimeModule, new PyIdeModule))
	}
	
}
