/**
 * generated by Xtext 2.15.0
 */
package org.xtext.comp.py;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>LExpr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.comp.py.LExpr#getLexpr <em>Lexpr</em>}</li>
 * </ul>
 *
 * @see org.xtext.comp.py.PyPackage#getLExpr()
 * @model
 * @generated
 */
public interface LExpr extends EObject
{
  /**
   * Returns the value of the '<em><b>Lexpr</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.comp.py.Expr}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lexpr</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lexpr</em>' containment reference list.
   * @see org.xtext.comp.py.PyPackage#getLExpr_Lexpr()
   * @model containment="true"
   * @generated
   */
  EList<Expr> getLexpr();

} // LExpr
