/**
 * generated by Xtext 2.15.0
 */
package org.xtext.comp.py;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Wh</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.comp.py.Wh#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see org.xtext.comp.py.PyPackage#getWh()
 * @model
 * @generated
 */
public interface Wh extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference.
   * @see #setElements(Program)
   * @see org.xtext.comp.py.PyPackage#getWh_Elements()
   * @model containment="true"
   * @generated
   */
  Program getElements();

  /**
   * Sets the value of the '{@link org.xtext.comp.py.Wh#getElements <em>Elements</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Elements</em>' containment reference.
   * @see #getElements()
   * @generated
   */
  void setElements(Program value);

} // Wh
