/**
 * generated by Xtext 2.15.0
 */
package org.xtext.compilation;

import org.xtext.compilation.AbstractWhile_lRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class While_lRuntimeModule extends AbstractWhile_lRuntimeModule {
}
