/**
 * generated by Xtext 2.15.0
 */
package org.xtext.comp.py;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Cons</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.comp.py.ExprCons#getLexpr <em>Lexpr</em>}</li>
 * </ul>
 *
 * @see org.xtext.comp.py.PyPackage#getExprCons()
 * @model
 * @generated
 */
public interface ExprCons extends EObject
{
  /**
   * Returns the value of the '<em><b>Lexpr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lexpr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lexpr</em>' containment reference.
   * @see #setLexpr(LExpr)
   * @see org.xtext.comp.py.PyPackage#getExprCons_Lexpr()
   * @model containment="true"
   * @generated
   */
  LExpr getLexpr();

  /**
   * Sets the value of the '{@link org.xtext.comp.py.ExprCons#getLexpr <em>Lexpr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lexpr</em>' containment reference.
   * @see #getLexpr()
   * @generated
   */
  void setLexpr(LExpr value);

} // ExprCons
