/**
 * generated by Xtext 2.15.0
 */
package org.xtext.comp.py;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Foreach</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.comp.py.Foreach#getExpr <em>Expr</em>}</li>
 *   <li>{@link org.xtext.comp.py.Foreach#getExpr2 <em>Expr2</em>}</li>
 *   <li>{@link org.xtext.comp.py.Foreach#getCmd <em>Cmd</em>}</li>
 * </ul>
 *
 * @see org.xtext.comp.py.PyPackage#getForeach()
 * @model
 * @generated
 */
public interface Foreach extends EObject
{
  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expr)
   * @see org.xtext.comp.py.PyPackage#getForeach_Expr()
   * @model containment="true"
   * @generated
   */
  Expr getExpr();

  /**
   * Sets the value of the '{@link org.xtext.comp.py.Foreach#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expr value);

  /**
   * Returns the value of the '<em><b>Expr2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr2</em>' containment reference.
   * @see #setExpr2(Expr)
   * @see org.xtext.comp.py.PyPackage#getForeach_Expr2()
   * @model containment="true"
   * @generated
   */
  Expr getExpr2();

  /**
   * Sets the value of the '{@link org.xtext.comp.py.Foreach#getExpr2 <em>Expr2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr2</em>' containment reference.
   * @see #getExpr2()
   * @generated
   */
  void setExpr2(Expr value);

  /**
   * Returns the value of the '<em><b>Cmd</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cmd</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cmd</em>' containment reference.
   * @see #setCmd(Commands)
   * @see org.xtext.comp.py.PyPackage#getForeach_Cmd()
   * @model containment="true"
   * @generated
   */
  Commands getCmd();

  /**
   * Sets the value of the '{@link org.xtext.comp.py.Foreach#getCmd <em>Cmd</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cmd</em>' containment reference.
   * @see #getCmd()
   * @generated
   */
  void setCmd(Commands value);

} // Foreach
